# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'ccapDemo' do
  pod 'ccap', :path => '..'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == "Pods-ccapDemo"
          puts "Updating #{target.name} OTHER_LDFLAGS"
          target.build_configurations.each do |config|
              xcconfig_path = config.base_configuration_reference.real_path
              xcconfig = File.read(xcconfig_path)
          end
      end
  end
end
